version: '3'

services:
  open-elevation:
    image: binakot/open-elevation
    container_name: open-elevation
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./data:/app/data
